# Where things are
source:       .
destination:  ./_site
plugins:      ./_plugins
layouts:      ./_layouts
paginate:     8

# Handling Reading
safe:         false
include:      [".htaccess"]
exclude:      []
keep_files:   [".git", ".svn"]
encoding:     "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext:  "textile"

# Filtering Content
show_drafts:  null
limit_posts:  0
future:       true
unpublished:  false

# Conversion
markdown:     kramdown
highlighter:  pygments
lsi:          false
excerpt_separator: "\n\n"

# Serving
detach:       false
port:         4000
host:         127.0.0.1
baseurl:      "" # does not include hostname

# Outputting
permalink:     date
paginate_path: /page:num 
timezone:      null


#站点基础配置
title: Vania
subTitle: Just Vania's  blog.
description: 这是 Vania 的博客。这里是用来快速记录工作，学习，生活的一点一滴的地方
url: http://vania123.github.io/vania-blog
#url: http://localhost:4000
feed: /atom.xml

#菜单配置
nav:
  - text: 首页
    url: /vania-blog/index.html
  - text: 文章归档
    url: /vania-blog/archives.html
  - text: 联系我
    url: 
  - text: 博客源代码
    url: 

#theme config
themes: /themes/violet

#配置你喜欢的顶部背景图片
headimg:
  - item: /vania-blog/themes/violet/images/hdbg01.jpg
  - item: /vania-blog/themes/violet/images/hdbg02.jpg
  - item: /vania-blog/themes/violet/images/hdbg03.jpg
  - item: /vania-blog/themes/violet/images/hdbg04.jpg

#关注我
follow:
  - class: fa-google-plus
    url: 
  - class: fa-facebook
    url: 
  - class: fa-github
    url: 
  - class: fa-weibo
    url: 
  - class: fa-renren
    url: 
  - class: fa-pinterest
    url: 
  - class: fa-twitter
    url: 
  - class: fa-rss
    url: 

#作者信息
author:
  link: 
  img: 
#评论信息
disqus:
  config: true
  id: piznblog

duoshuo:
  config: false
  id: zhanxin